/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx,js,jsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#a3c9ff',
        'outline-variant': '#c2c6d2',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001c39',
        'primary-fixed': '#d4e3ff',
        background: '#f9f9ff',
        error: '#ba1a1a',
        'tertiary-fixed': '#d3e3ff',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#bec8d0',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#385f8f',
        surface: '#f9f9ff',
        primary: '#004782',
        'surface-container-high': '#e2e8f8',
        'on-secondary-container': '#5b646b',
        tertiary: '#1d4776',
        'surface-container-highest': '#dce2f3',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-bright': '#f9f9ff',
        outline: '#727782',
        'surface-dim': '#d3daea',
        'secondary-container': '#d8e1ea',
        'secondary-fixed': '#dbe4ec',
        'on-surface': '#151c27',
        'on-background': '#151c27',
        'on-primary-fixed-variant': '#004883',
        'on-secondary-fixed-variant': '#3f484f',
        'surface-container': '#e7eefe',
        'primary-container': '#185fa5',
        'on-error': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'on-secondary-fixed': '#141d23',
        'on-tertiary-container': '#c0d9ff',
        'on-surface-variant': '#424751',
        'on-tertiary-fixed-variant': '#1e4877',
        'on-tertiary-fixed': '#001c39',
        'primary-fixed-dim': '#a4c9ff',
        secondary: '#565f67',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'on-secondary': '#ffffff',
        'surface-tint': '#1960a6',
        'on-primary-container': '#c1d9ff',
        'inverse-primary': '#a4c9ff',
        'surface-variant': '#dce2f3',
        success: '#16A34A',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '4px',
        'margin-desktop': '32px',
        '2xl': '48px',
        sm: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
        xl: '32px',
        lg: '24px',
        md: '16px',
      },
      fontFamily: {
        'label-md': ['DM Sans', 'sans-serif'],
        'label-sm': ['DM Sans', 'sans-serif'],
        'headline-md': ['DM Sans', 'sans-serif'],
        'headline-sm': ['DM Sans', 'sans-serif'],
        'body-sm': ['DM Sans', 'sans-serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'display-lg': ['DM Sans', 'sans-serif'],
        'display-lg-mobile': ['DM Sans', 'sans-serif'],
        sans: ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
